# install postgresql on remote instance

 
- name: install postgresql 12 on Ubuntu or Debian 10
  hosts: home
  become: yes
  become_method: sudo
  gather_facts: yes
 
  tasks:
  - debug: msg="play_hosts={{play_hosts}}"
  - debug: msg="ansible_distribution={{ansible_distribution}}"
 
  - name: postgresql key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present
    become: true
     
  - name: create variable
    command: bash -c "echo \"deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main\" "
    register: repo_line
 
  - debug: 
      msg: "{{ repo_line.stdout }}"
       
  - name: add postgresql repo 
    apt_repository:
      repo: "{{ repo_line.stdout }}"
      state: present
    become: true
 
  - name: install postgresql
    apt:
      name: "postgresql-12"
      state: present
      update_cache: yes
    become: true
